/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_status.h"
#include "bar_powerline_tags.h"
#include "bar_status.h"
#include "bar_winicon.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cyclelayouts.h"
#include "focusmaster.h"
#include "fullscreen.h"
#include "keymodes.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "scratchpad.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tagothermonitor.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_monocle.h"
#include "layout_tile.h"

