/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_status.c"
#include "bar_powerline_tags.c"
#include "bar_status.c"
#include "bar_winicon.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "focusmaster.c"
#include "fullscreen.c"
#include "keymodes.c"
#include "movestack.c"
#include "pertag.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tagothermonitor.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_monocle.c"
#include "layout_tile.c"

